In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [69]:
path = (r"C:\Users\HP\Desktop\AI_project\week-05-visualization-first-models-and-ML\datasets\students.csv")

In [70]:
df = pd.read_csv(path,usecols=['study_hours' ,"final_marks" ])

In [71]:
df.head()

,study_hours,final_marks
0,8.1,68.5
1,5.2,54.4
2,4.0,68.7
3,2.5,56.8
4,7.7,68.8


In [72]:
df.shape

(184, 2)

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   study_hours  179 non-null    float64
 1   final_marks  184 non-null    float64
dtypes: float64(2)
memory usage: 3.0 KB


In [74]:
df.describe()

,study_hours,final_marks
count,179.000000,184.000000
mean,7.256983,65.119565
std,4.888808,11.508669
min,0.500000,32.100000
25%,3.650000,58.175000
50%,6.400000,65.700000
75%,8.850000,72.725000
max,30.000000,92.400000


In [75]:
df['study_hours']

0      8.1
1      5.2
2      4.0
3      2.5
4      7.7
      ... 
179    5.5
180    3.5
181    1.4
182    7.9
183    6.3
Name: study_hours, Length: 184, dtype: float64

In [76]:
df['study_hours'] = df['study_hours'].fillna(df['study_hours'].mean())

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   study_hours  184 non-null    float64
 1   final_marks  184 non-null    float64
dtypes: float64(2)
memory usage: 3.0 KB


In [78]:
df['study_hours'] = df['study_hours'].fillna(df['study_hours'].median())

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   study_hours  184 non-null    float64
 1   final_marks  184 non-null    float64
dtypes: float64(2)
memory usage: 3.0 KB


In [80]:
df.shape

(184, 2)

In [81]:
x_train = df['study_hours'].iloc[0:147]
y_train = df['final_marks'].iloc[0:147]

In [82]:
x_test = df['study_hours'].iloc[147:]
y_test = df['final_marks'].iloc[147:]

In [83]:
x_train

0       8.1
1       5.2
2       4.0
3       2.5
4       7.7
       ... 
142    17.2
143    18.9
144     6.2
145     3.5
146    19.9
Name: study_hours, Length: 147, dtype: float64

In [84]:
y_train

0      68.5
1      54.4
2      68.7
3      56.8
4      68.8
       ... 
142    78.0
143    79.1
144    52.3
145    62.3
146    88.4
Name: final_marks, Length: 147, dtype: float64

In [85]:
x_train= np.array(x_train)
y_train= np.array(y_train)
x_test= np.array(x_test)
y_test= np.array(y_test)

In [86]:
class LinearRegression:
    count = 0
    def __init__(self, m=0, b=0, alpha=0):
        self.alpha = alpha
        self.m = m
        self.b = b
        self.history = []

    def predict(self, x) :
        return self.m * x + self.b

    def cost(self, x, y):
        y_hat = self.predict(x)
        error = y_hat - y
        loss = (1/(2*len(x)) )* np.sum(error**2)
        return loss

    def gradeint(self,x ,y):
        y_hat = self.predict(x)
        error = y_hat - y
        gm = np.sum (error* x) /len(x)
        gb = np.sum(error) /len(x)
        return gm,gb

    def run_epoch(self,x,y):
        gm, gb = self.gradeint(x,y)
        self.m -= self.alpha * gm
        self.b -= self.alpha * gb
        loss = self.cost(x,y)
        self.history.append((self.m, self.b, loss))
        self.count += 1
        print(f"Epoch : {self.count} -- m : {self.m} -- b : {self.b} -- cost : {loss}")


    def fit(self,epoch ,x,y):
        for i in range( 1,epoch+1):
            self.run_epoch(x,y)

In [87]:
model = LinearRegression(1,1,0.01)
model.fit(700, x_train,y_train)

Epoch : 1 -- m : 5.232264870541083 -- b : 1.5682935431155702 -- cost : 535.0446231973267
Epoch : 2 -- m : 6.18906570358156 -- b : 1.8236518221462896 -- cost : 473.7624720826851
Epoch : 3 -- m : 6.396161179056569 -- b : 2.0069950614595276 -- cost : 468.04332702241436
Epoch : 4 -- m : 6.431688391578847 -- b : 2.173470231125182 -- cost : 465.2507313131026
Epoch : 5 -- m : 6.427980759853007 -- b : 2.3357014582561906 -- cost : 462.62677757986813
Epoch : 6 -- m : 6.415328821958863 -- b : 2.4965795383303546 -- cost : 460.0268751444302
Epoch : 7 -- m : 6.400665862704679 -- b : 2.656767338099107 -- cost : 457.4433549416931
Epoch : 8 -- m : 6.385578774774345 -- b : 2.8164177557166297 -- cost : 454.87572229485187
Epoch : 9 -- m : 6.370430680991576 -- b : 2.975566955734076 -- cost : 452.32385898934876
Epoch : 10 -- m : 6.355304587939787 -- b : 3.1342243792067337 -- cost : 449.7876671016402
Epoch : 11 -- m : 6.340219384929229 -- b : 3.2923933466994897 -- cost : 447.26705033462855
Epoch : 12 -- m : 

In [88]:
m = 1
b = 1
alpha = 0.01

model = LinearRegression(m,b,alpha)

In [89]:
model.b

1

In [90]:
model.m

1

In [91]:
model.alpha

0.01

In [92]:
model.run_epoch(x_train , y_train)


Epoch : 1 -- m : 5.232264870541083 -- b : 1.5682935431155702 -- cost : 535.0446231973267


In [ ]:
for i in range(8,500):

    model.run_epoch(x_train , y_train)
    

Epoch : 2 -- m : 6.18906570358156 -- b : 1.8236518221462896 -- cost : 473.7624720826851
Epoch : 3 -- m : 6.396161179056569 -- b : 2.0069950614595276 -- cost : 468.04332702241436
Epoch : 4 -- m : 6.431688391578847 -- b : 2.173470231125182 -- cost : 465.2507313131026
Epoch : 5 -- m : 6.427980759853007 -- b : 2.3357014582561906 -- cost : 462.62677757986813
Epoch : 6 -- m : 6.415328821958863 -- b : 2.4965795383303546 -- cost : 460.0268751444302
Epoch : 7 -- m : 6.400665862704679 -- b : 2.656767338099107 -- cost : 457.4433549416931
Epoch : 8 -- m : 6.385578774774345 -- b : 2.8164177557166297 -- cost : 454.87572229485187
Epoch : 9 -- m : 6.370430680991576 -- b : 2.975566955734076 -- cost : 452.32385898934876
Epoch : 10 -- m : 6.355304587939787 -- b : 3.1342243792067337 -- cost : 449.7876671016402
Epoch : 11 -- m : 6.340219384929229 -- b : 3.2923933466994897 -- cost : 447.26705033462855
Epoch : 12 -- m : 6.3251792853937685 -- b : 3.4500757742527397 -- cost : 444.76191303629747
Epoch : 13 -- m

In [94]:
y_test

array([53. , 76.1, 90.4, 53.4, 62.8, 70.1, 75.3, 64.4, 57.2, 40.9, 74.1,
       73.5, 32.1, 46.8, 70.8, 68. , 65.7, 64.1, 80.5, 75.1, 72.5, 64.5,
       74.4, 72.7, 64.8, 49.9, 51.2, 91.8, 65.1, 67.4, 70.3, 60.9, 56. ,
       63.5, 65.3, 71.5, 57.8])

In [95]:
y_train

array([68.5, 54.4, 68.7, 56.8, 68.8, 55.4, 48.3, 62.5, 92.4, 79.3, 54.4,
       67.7, 42.7, 68.5, 69. , 60.1, 75.3, 64. , 60.4, 72.1, 48.3, 48.8,
       66.6, 60.4, 63.3, 80. , 59.6, 76. , 63.8, 68.8, 73. , 85.8, 53.8,
       69. , 62.6, 85. , 58.5, 50.9, 76.6, 44.5, 71.2, 45.1, 61.3, 65.6,
       73.9, 69.4, 45.1, 65.9, 68.7, 62.3, 76.1, 70.4, 67.6, 68.8, 70.8,
       61.1, 83.9, 76.6, 68.2, 67. , 55.5, 65.2, 57.4, 68. , 52.9, 65.6,
       67.3, 80.6, 63. , 60.9, 77.5, 47. , 78. , 68.1, 53.6, 84.8, 53.4,
       80.9, 68.3, 75.6, 42.1, 72.9, 62.5, 74.5, 56.1, 77.4, 59.5, 60.8,
       83. , 85.5, 70.9, 61.2, 73.5, 60.3, 73.5, 59.2, 82.6, 82.4, 72.6,
       78. , 45.5, 56.8, 43.6, 66.4, 59.8, 61.2, 48.2, 68.4, 42.2, 64. ,
       72.8, 48.5, 49.8, 63.7, 58.5, 72.1, 38.1, 52.4, 71.4, 78. , 48.2,
       53.8, 71.2, 72.2, 42.5, 71.2, 62.4, 58.3, 56.1, 46.5, 71.5, 59.5,
       68.1, 60.3, 70.6, 74.1, 86. , 65.3, 65.7, 65.7, 77.7, 64. , 78. ,
       79.1, 52.3, 62.3, 88.4])

In [96]:
x_test_pred =model.predict(x_test)


In [97]:
x_test_pred

array([52.41121795, 65.19978543, 89.49806366, 59.31704439, 59.82858709,
       62.13052924, 65.19978543, 70.82675513, 57.27087359, 48.06310501,
       78.24412427, 66.73441353, 46.78424826, 49.85350445, 73.38446863,
       61.36321519, 62.13052924, 56.75933089, 91.03269175, 66.47864218,
       59.06127304, 50.1092758 , 74.15178267, 65.71132813, 58.03818764,
       54.2016174 , 45.50539151, 91.2884631 , 55.2247028 , 57.27087359,
       54.7131601 , 49.34196175, 57.01510224, 51.89967525, 46.52847691,
       63.15361464, 59.06127304])

In [98]:
y_test

array([53. , 76.1, 90.4, 53.4, 62.8, 70.1, 75.3, 64.4, 57.2, 40.9, 74.1,
       73.5, 32.1, 46.8, 70.8, 68. , 65.7, 64.1, 80.5, 75.1, 72.5, 64.5,
       74.4, 72.7, 64.8, 49.9, 51.2, 91.8, 65.1, 67.4, 70.3, 60.9, 56. ,
       63.5, 65.3, 71.5, 57.8])

In [99]:
model.cost(x_test,y_test)

np.float64(36.24146180229899)

In [100]:
model.history

[(np.float64(5.232264870541083),
  np.float64(1.5682935431155702),
  np.float64(535.0446231973267)),
 (np.float64(6.18906570358156),
  np.float64(1.8236518221462896),
  np.float64(473.7624720826851)),
 (np.float64(6.396161179056569),
  np.float64(2.0069950614595276),
  np.float64(468.04332702241436)),
 (np.float64(6.431688391578847),
  np.float64(2.173470231125182),
  np.float64(465.2507313131026)),
 (np.float64(6.427980759853007),
  np.float64(2.3357014582561906),
  np.float64(462.62677757986813)),
 (np.float64(6.415328821958863),
  np.float64(2.4965795383303546),
  np.float64(460.0268751444302)),
 (np.float64(6.400665862704679),
  np.float64(2.656767338099107),
  np.float64(457.4433549416931)),
 (np.float64(6.385578774774345),
  np.float64(2.8164177557166297),
  np.float64(454.87572229485187)),
 (np.float64(6.370430680991576),
  np.float64(2.975566955734076),
  np.float64(452.32385898934876)),
 (np.float64(6.355304587939787),
  np.float64(3.1342243792067337),
  np.float64(449.7876671

In [120]:
path = (r"C:\Users\HP\Desktop\AI_project\week-05-visualization-first-models-and-ML\datasets\students.csv")

In [121]:
df = pd.read_csv(path,usecols=['study_hours' ,"attendance" ])

In [122]:
df

,study_hours,attendance
0,8.1,87.5
1,5.2,77.4
2,4.0,96.9
3,2.5,100.0
4,7.7,87.8
...,...,...
179,5.5,68.6
180,3.5,70.1
181,1.4,82.0
182,7.9,97.8


In [123]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   study_hours  179 non-null    float64
 1   attendance   168 non-null    float64
dtypes: float64(2)
memory usage: 3.0 KB


In [124]:
df['study_hours'] = df['study_hours'].fillna(df['study_hours'].median())

In [126]:
df['attendance'] = df['attendance'].fillna(df['attendance'].median())

In [127]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   study_hours  184 non-null    float64
 1   attendance   184 non-null    float64
dtypes: float64(2)
memory usage: 3.0 KB


In [128]:
x_train =np.array(df['study_hours'].iloc[0:147])
y_train =np.array(df['attendance'].iloc[0:147])
y_test =np.array(df['attendance'].iloc[147])
y_test =np.array(df['attendance'].iloc[147])

In [129]:
class LinearRegression:
    count = 0
    def __init__(self, m=0, b=0, alpha=0):
        self.alpha = alpha
        self.m = m
        self.b = b
        self.history = []

    def predict(self, x) :
        return self.m * x + self.b

    def cost(self, x, y):
        y_hat = self.predict(x)
        error = y_hat - y
        loss = (1/(2*len(x))) * np.sum(error**2)
        return loss

    def gradeint(self,x ,y):
        y_hat = self.predict(x)
        error = y_hat - y
        gm = np.sum (error* x) /len(x)
        gb = np.sum(error) /len(x)
        return gm,gb

    def run_epoch(self,x,y):
        gm, gb = self.gradeint(x,y)
        self.m -= self.alpha * gm
        self.b -= self.alpha * gb
        loss = self.cost(x,y)
        self.history.append((self.m, self.b, loss))
        self.count += 1
        print(f"Epoch : {self.count} -- m : {self.m} -- b : {self.b} -- cost : {loss}")


    def fit(self,epoch ,x,y):
        for i in range( 1,epoch+1):
            self.run_epoch(x,y)

In [ ]:

model1 = LinearRegression(0,0,0.01)

In [145]:
for e in range(8,1000):
    model1.run_epoch(x_train,y_train)
    

Epoch : 1 -- m : 5.897529931972789 -- b : 0.822639455782313 -- cost : 1241.337298609956
Epoch : 2 -- m : 7.252287776214077 -- b : 1.210624995599056 -- cost : 1116.3851879404451
Epoch : 3 -- m : 7.549107742124642 -- b : 1.4967733934432053 -- cost : 1103.3907090040325
Epoch : 4 -- m : 7.59959549461193 -- b : 1.758598406508482 -- cost : 1096.5073189891607
Epoch : 5 -- m : 7.592771009239708 -- b : 2.0141545958295866 -- cost : 1089.9935793066356
Epoch : 6 -- m : 7.572656206602281 -- b : 2.267648675332455 -- cost : 1083.5378338019384
Epoch : 7 -- m : 7.549503461926583 -- b : 2.5200622374228336 -- cost : 1077.1229435232058
Epoch : 8 -- m : 7.525700340574561 -- b : 2.771625749083859 -- cost : 1070.7477458162612
Epoch : 9 -- m : 7.501802721418691 -- b : 3.022394737035422 -- cost : 1064.4119460340519
Epoch : 10 -- m : 7.477939890425229 -- b : 3.2723839792843923 -- cost : 1058.1152980419831
Epoch : 11 -- m : 7.45414178209236 -- b : 3.521598757890666 -- cost : 1051.8575597590273
Epoch : 12 -- m : 

In [146]:
model1.run_epoch(x_train , y_train)

Epoch : 993 -- m : 0.15208949043612524 -- b : 79.97998820054468 -- cost : 47.72975076636046


In [147]:
y_test

array(68.2)

In [149]:
y_train

array([ 87.5,  77.4,  96.9, 100. ,  87.8,  79.2,  81.3,  90.4,  78.7,
        79.2,  92.1,  82.7,  82.7,  87.5,  87.9,  92.4,  82.7,  80. ,
        74.8,  87.3,  73.8,  78.8,  83.2,  58. ,  70.5,  83.8,  82.4,
        75.5,  82. ,  82.7, 100. ,  63.6,  87.2,  89.4,  79.6, 100. ,
        69.1,  83.3,  82.7,  82.7,  87.3,  72.5,  86.2,  81.3,  82.7,
        90.3, 100. ,  86.1,  80.2,  91.2,  91.1,  95.6,  97.8,  81.9,
        74.1,  82.7,  89.6,  84.4,  89.8,  78.7,  78.7,  84.2,  69.5,
       100. ,  82. ,  79.8,  78.8, 100. ,  82.7,  76. ,  80.7,  67.1,
        86.5,  86.1,  82.7,  69.5,  56.8,  77.1,  82.7,  82.7,  54.2,
        82.7,  65.5,  88.5,  71. ,  99.2,  83.5,  80.7,  82.7,  63.5,
        71.7,  83.3,  74.3,  86.9,  83.4,  86.2,  99.3,  95.6,  82.6,
        82.7,  82.4,  90.8,  85.8,  78.4,  84.8,  83.3,  72.9,  77.1,
        62.9,  84.7,  91.5,  87.6,  86.5,  69.7,  55.8,  98.6,  65.7,
        76.2,  65.1,  78. ,  77.7,  78.6,  91.9,  87.3,  79.1,  93.7,
        81.1,  77.6,

In [ ]:
for 